// Kept in sync with packages/shared/src/upiProvider.js UPI_PROVIDER_OPTIONS.
export const UPI_PROVIDER_OPTIONS = [
  'Airtel Merchant',
  'Airtel Money',
  'Amazon Pay',
  'AU Small Finance Bank',
  'Axis Bank',
  'Bajaj Pay',
  'Bank of Baroda',
  'Bank of India',
  'BHIM',
  'Canara Bank',
  'Central Bank',
  'CRED',
  'Equitas Bank',
  'Federal Bank',
  'Fi Money',
  'Freecharge',
  'Google Pay',
  'Google Pay Merchant',
  'Groww',
  'HDFC Bank',
  'ICICI Bank',
  'IDFC Bank',
  'IndusInd Bank',
  'IOB',
  'JioMoney',
  'Jupiter',
  'Kotak Bank',
  'MobiKwik',
  'Navi',
  'Niyogin',
  'Paytm',
  'PhonePe',
  'PNB',
  'RBL Bank',
  'SBI',
  'Slice',
  'TrueBalance',
  'Ujjivan Bank',
  'Union Bank',
  'WhatsApp Pay',
  'Yes Bank',
];
