const PAYMENT_STATUSES = ['pending', 'paid', 'expired', 'cancelled', 'failed'];

const UPI_TYPES = ['merchant', 'personal'];

const MERCHANT_STATUSES = ['active', 'suspended'];

const MERCHANT_USER_ROLES = ['merchant_admin', 'merchant_staff'];

const PLATFORM_ADMIN_ROLES = ['superadmin', 'support'];

const CONFIRMATION_SOURCES = ['forwarder', 'manual'];

const WEBHOOK_EVENTS = ['payment.paid', 'payment.expired'];

const ERROR_CODES = {
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  INVALID_AMOUNT: 'INVALID_AMOUNT',
  UPI_ACCOUNT_REQUIRED: 'UPI_ACCOUNT_REQUIRED',
  UPI_ACCOUNT_INACTIVE: 'UPI_ACCOUNT_INACTIVE',
  UPI_ACCOUNT_NOT_FOUND: 'UPI_ACCOUNT_NOT_FOUND',
  UPI_PROVIDER_REQUIRED: 'UPI_PROVIDER_REQUIRED',
  AMOUNT_ALREADY_PENDING: 'AMOUNT_ALREADY_PENDING',
  PAYMENT_NOT_FOUND: 'PAYMENT_NOT_FOUND',
  PAYMENT_NOT_PENDING: 'PAYMENT_NOT_PENDING',
  MERCHANT_ORDER_REF_CONFLICT: 'MERCHANT_ORDER_REF_CONFLICT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  MERCHANT_SUSPENDED: 'MERCHANT_SUSPENDED',
  NOT_FOUND: 'NOT_FOUND',
  RATE_LIMITED: 'RATE_LIMITED',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

module.exports = {
  PAYMENT_STATUSES,
  UPI_TYPES,
  MERCHANT_STATUSES,
  MERCHANT_USER_ROLES,
  PLATFORM_ADMIN_ROLES,
  CONFIRMATION_SOURCES,
  WEBHOOK_EVENTS,
  ERROR_CODES,
};
